// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RIIMS.Infrastructure;

#nullable disable

namespace RIIMS.Infrastructure.Migrations
{
    [DbContext(typeof(RiimsDbContext))]
    [Migration("20241229185234_IdentityUser")]
    partial class IdentityUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Aftesite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Aftesite");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Departamenti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.ToTable("Departamenti");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Edukimi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("FushaStudimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("NiveliAkademikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("NiveliAkademikId");

                    b.HasIndex("UserId");

                    b.ToTable("Edukimi");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Eksperienca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LlojiLokacionit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlojiPunesimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Eksperienca");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Gjuhet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmriGjuhes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gjuhet");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.HonorsAndAwards", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dataEleshimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("issuer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pershkrimi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("HonorsAndAwards");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Institucioni", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Institucioni");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Licensat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CredentialId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredentialUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataLeshimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSkadimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Licensat");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.MbikqyresITemave", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DepartamentiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("studenti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulliTemes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentiId");

                    b.HasIndex("UserId");

                    b.ToTable("MbikqyresITemave");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.NiveliAkademik", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("lvl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NiveliAkademik");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.NiveliGjuhesor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Niveli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NiveliGjuhesor");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Projekti", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("collaborators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("emriProjektit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Projekti");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Publikimi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("AutoriKryesor")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataPublikimi")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartamentiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkuPublikimit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LlojiPublikimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentiId");

                    b.HasIndex("UserId");

                    b.ToTable("Publikimi");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.PunaVullnetare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("PunaVullnetare");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Specializimet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstitucioniId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("aftesiteEfituara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dataEFillimit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("dataEMbarimit")
                        .HasColumnType("datetime2");

                    b.Property<string>("llojiIspecializimit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lokacionit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("nrKredive")
                        .HasColumnType("int");

                    b.Property<string>("pershkrimi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstitucioniId");

                    b.HasIndex("UserId");

                    b.ToTable("Specializimet");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("NiveliAkademikId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("dataELindjes")
                        .HasColumnType("datetime2");

                    b.Property<string>("emri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gjinia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mbiemri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("numriTelefonit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("NiveliAkademikId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.UserGjuhet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GjuhaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("NiveliGjuhesorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GjuhaId");

                    b.HasIndex("NiveliGjuhesorId");

                    b.HasIndex("UserId");

                    b.ToTable("UserGjuhet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Aftesite", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Aftesia")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Aftesite")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Departamenti", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Departamentet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Edukimi", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Edukimet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.NiveliAkademik", "NiveliAkademik")
                        .WithMany("Edukimet")
                        .HasForeignKey("NiveliAkademikId");

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Edukimet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("NiveliAkademik");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Eksperienca", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Eksperiencat")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Eksperiencat")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.HonorsAndAwards", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("HonorsAndAwards")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("HonorsAndAwards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Licensat", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Licensat")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Licensat")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.MbikqyresITemave", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Departamenti", "Departamenti")
                        .WithMany()
                        .HasForeignKey("DepartamentiId");

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("MbiKqyresitETemave")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamenti");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Projekti", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Projektet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Projektet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Publikimi", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Departamenti", "Departamenti")
                        .WithMany()
                        .HasForeignKey("DepartamentiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Publikimet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamenti");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.PunaVullnetare", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("PunetVullnetare")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("PunetVullnetare")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Specializimet", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Institucioni", "Institucioni")
                        .WithMany("Specializimet")
                        .HasForeignKey("InstitucioniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Specializimet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institucioni");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.User", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Image", "Image")
                        .WithMany("Users")
                        .HasForeignKey("ImageId");

                    b.HasOne("RIIMS.Domain.Entities.NiveliAkademik", "NiveliAkademik")
                        .WithMany("Users")
                        .HasForeignKey("NiveliAkademikId");

                    b.Navigation("Image");

                    b.Navigation("NiveliAkademik");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.UserGjuhet", b =>
                {
                    b.HasOne("RIIMS.Domain.Entities.Gjuhet", "Gjuha")
                        .WithMany("UserGjuhet")
                        .HasForeignKey("GjuhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.NiveliGjuhesor", "NiveliGjuhesor")
                        .WithMany("UserGjuhet")
                        .HasForeignKey("NiveliGjuhesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RIIMS.Domain.Entities.User", "User")
                        .WithMany("Gjuhet")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gjuha");

                    b.Navigation("NiveliGjuhesor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Gjuhet", b =>
                {
                    b.Navigation("UserGjuhet");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Image", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.Institucioni", b =>
                {
                    b.Navigation("Aftesia");

                    b.Navigation("Departamentet");

                    b.Navigation("Edukimet");

                    b.Navigation("Eksperiencat");

                    b.Navigation("HonorsAndAwards");

                    b.Navigation("Licensat");

                    b.Navigation("Projektet");

                    b.Navigation("PunetVullnetare");

                    b.Navigation("Specializimet");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.NiveliAkademik", b =>
                {
                    b.Navigation("Edukimet");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.NiveliGjuhesor", b =>
                {
                    b.Navigation("UserGjuhet");
                });

            modelBuilder.Entity("RIIMS.Domain.Entities.User", b =>
                {
                    b.Navigation("Aftesite");

                    b.Navigation("Edukimet");

                    b.Navigation("Eksperiencat");

                    b.Navigation("Gjuhet");

                    b.Navigation("HonorsAndAwards");

                    b.Navigation("Licensat");

                    b.Navigation("MbiKqyresitETemave");

                    b.Navigation("Projektet");

                    b.Navigation("Publikimet");

                    b.Navigation("PunetVullnetare");

                    b.Navigation("Specializimet");
                });
#pragma warning restore 612, 618
        }
    }
}
